name: fchat3-log-merger
about: Reads multiple F-Chat 3.0 client log folders and merges them together

settings:
  - ArgRequiredElseHelp

args:
  - folders:
      help: What folders to read from.
      short: f
      long: folder
      multiple: true
      takes_value: true
      required: true
  - time-diff:
      help: How long the time difference between messages to check for duplicates specified in human time. Defaults to 5min.
      short: d
      long: time-diff
      takes_value: true
  - output:
      help: Folder to write the merged logs to.
      short: o
      long: output
      takes_value: true
      required_unless: dry-run
  - dry-run:
      help: Collects files, but does not do anything.
      long: dry-run
      takes_value: false
      required: false
  - dupe-warning:
      help: Indicate if a file has more than two duplicate messages in the comparison window.
      long: dupe-warning
      takes_value: false
      required: false